services:
  app:
    image: php:8.2-apache
    container_name: app
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./app/conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8080:80
    networks:
      - dev
  db:
    image: mysql
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
networks:
  dev:

volumes:
  db-data: